/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.practica.banca_1.interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author jeffe
 */
public class frmMenu1 extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu1
     */
    public frmMenu1() {
        initComponents();
          this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmClientesEmpleados = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiCuenta = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmCoches = new javax.swing.JMenu();
        jmiRegistrarCoches = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmVentas = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiConCuenta = new javax.swing.JMenuItem();
        jmiConMovi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jmClientesEmpleados.setBackground(new java.awt.Color(153, 153, 153));
        jmClientesEmpleados.setBorder(null);
        jmClientesEmpleados.setText("Clientes");

        jmiClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmiClientes.setText("Clientes");
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jmClientesEmpleados.add(jmiClientes);
        jmClientesEmpleados.add(jSeparator1);

        jMenuBar1.add(jmClientesEmpleados);

        jmiCuenta.setText("Cuenta");
        jmiCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCuentaActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cuenta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmiCuenta.add(jMenuItem1);

        jMenuBar1.add(jmiCuenta);

        jmCoches.setBackground(new java.awt.Color(255, 255, 255));
        jmCoches.setBorder(null);
        jmCoches.setText("Movimientos");

        jmiRegistrarCoches.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jmiRegistrarCoches.setText("Registrar Movimiento");
        jmiRegistrarCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarCochesActionPerformed(evt);
            }
        });
        jmCoches.add(jmiRegistrarCoches);

        jMenuBar1.add(jmCoches);

        jmSalir.setBackground(new java.awt.Color(153, 153, 153));
        jmSalir.setBorder(null);
        jmSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        jmSalir.add(jSeparator3);

        jMenuBar1.add(jmSalir);

        jmVentas.setBackground(new java.awt.Color(153, 153, 153));
        jmVentas.setBorder(null);
        jmVentas.setText("Consultas");
        jmVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmVentasMouseClicked(evt);
            }
        });
        jmVentas.add(jSeparator2);

        jmiConCuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jmiConCuenta.setText("Cuentas");
        jmiConCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConCuentaActionPerformed(evt);
            }
        });
        jmVentas.add(jmiConCuenta);

        jmiConMovi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmiConMovi.setText("Movimientos");
        jmiConMovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConMoviActionPerformed(evt);
            }
        });
        jmVentas.add(jmiConMovi);

        jMenuBar1.add(jmVentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        // TODO add your handling code here:
        JDClientes clientes=new JDClientes(this,true);//creMOA UN NOMBRE DE LA VENTANA HIJA LO INSTANCIAMOS
        clientes.setVisible(true);
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmCuenta cu = new FrmCuenta();
        cu.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCuentaActionPerformed
        // TODO add your handling code here:
        FrmCuenta cu = new FrmCuenta();
        cu.setVisible(true);
    }//GEN-LAST:event_jmiCuentaActionPerformed

    private void jmiRegistrarCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarCochesActionPerformed
        // TODO add your handling code here:
        JDMovimientos productos=new JDMovimientos(this,true);
        productos.setVisible(true);
    }//GEN-LAST:event_jmiRegistrarCochesActionPerformed

    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_NO_OPTION == resp){
            System.exit(0);
        }
        else{

        }

    }//GEN-LAST:event_jmSalirMouseClicked

    private void jmiConCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConCuentaActionPerformed
        // TODO add your handling code here:
        FrmConCuenta cu = new FrmConCuenta(this,true);
        cu.setVisible(true);
    }//GEN-LAST:event_jmiConCuentaActionPerformed

    private void jmiConMoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConMoviActionPerformed
        // TODO add your handling code here:
        JDConMovimiento conMovi = new JDConMovimiento(this,true);
        conMovi.setVisible(true);
    }//GEN-LAST:event_jmiConMoviActionPerformed

    private void jmVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmVentasMouseClicked
        // TODO add your handling code here:
        //JDVenta venta=new JDVenta(this,true);
        //venta.setVisible(true);
    }//GEN-LAST:event_jmVentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu jmClientesEmpleados;
    private javax.swing.JMenu jmCoches;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenu jmVentas;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiConCuenta;
    private javax.swing.JMenuItem jmiConMovi;
    private javax.swing.JMenu jmiCuenta;
    private javax.swing.JMenuItem jmiRegistrarCoches;
    // End of variables declaration//GEN-END:variables
}
