/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.practica.banca_1.interfaces;

import ec.edu.espe.practica.banca_1.clases.Clientes;
import ec.edu.espe.practica.banca_1.clases.Movimientos;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author jeffe
 */
public class JDMovimientos extends javax.swing.JDialog {
   Date now = new Date(System.currentTimeMillis());
    SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
    String fecha = String.valueOf(date);
    Movimientos obj;
    Clientes cli;
    java.util.Date dt = new java.util.Date();
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    String currentTime = sdf.format(dt);
    /**
     * Creates new form JDMovimientos1
     */
    public JDMovimientos(java.awt.Frame parent, boolean modal) {
         super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        obj = new Movimientos();
        obj.generarCodigo(txtCodigo);
        txtFecha.setText(currentTime);
        cli = new Clientes();
        jcmbTipo.enable(false);
        txtMonto.enable(false);
    }
     public void Limpiar(){        
        txtCodigo.setText("");
        txtFecha.setText("");
        txtMonto.setText("");
        txtSaldo.setText("");
        jcmbCuenta.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMantenimientoTitulo = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblIngresarID = new javax.swing.JLabel();
        txtBuscarCI = new javax.swing.JTextField();
        btnClienteBuscarCI = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        btnMovEliminar = new javax.swing.JButton();
        btnMovGuardar = new javax.swing.JButton();
        btnMovNuevo = new javax.swing.JButton();
        btnMovSalir = new javax.swing.JButton();
        jcmbCuenta = new javax.swing.JComboBox<>();
        pnlDatosMov = new javax.swing.JPanel();
        jcmbTipo = new javax.swing.JComboBox<>();
        txtCodigoCuenta = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblMantenimientoTipo = new javax.swing.JLabel();
        lblMantenimientoStock = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        lblMantenimientoNombre = new javax.swing.JLabel();
        lblMantenimientoCodigo = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblMantenimientoCodigo2 = new javax.swing.JLabel();
        lblMantenimientoTipo1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMantenimientoTitulo.setBackground(new java.awt.Color(204, 204, 204));
        pnlMantenimientoTitulo.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        jLabel1.setText("MOVIMIENTOS");

        javax.swing.GroupLayout pnlMantenimientoTituloLayout = new javax.swing.GroupLayout(pnlMantenimientoTitulo);
        pnlMantenimientoTitulo.setLayout(pnlMantenimientoTituloLayout);
        pnlMantenimientoTituloLayout.setHorizontalGroup(
            pnlMantenimientoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMantenimientoTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(173, 173, 173)
                .addComponent(jLabel2))
        );
        pnlMantenimientoTituloLayout.setVerticalGroup(
            pnlMantenimientoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMantenimientoTituloLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlMantenimientoTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIngresarID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIngresarID.setText("Ingresar CI:");

        txtBuscarCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCIKeyTyped(evt);
            }
        });

        btnClienteBuscarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteBuscarCIActionPerformed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        btnMovEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovEliminarActionPerformed(evt);
            }
        });

        btnMovGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovGuardarActionPerformed(evt);
            }
        });

        btnMovNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovNuevoActionPerformed(evt);
            }
        });

        btnMovSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnMovEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMovSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnMovGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnMovNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMovGuardar)
                    .addComponent(btnMovNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMovEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMovSalir))
                .addGap(127, 127, 127))
        );

        jcmbCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbCuentaActionPerformed(evt);
            }
        });

        pnlDatosMov.setBackground(new java.awt.Color(204, 255, 255));

        jcmbTipo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jcmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retiro", "Depósito" }));

        txtCodigoCuenta.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCodigoCuenta.setEnabled(false);

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCodigo.setEnabled(false);

        lblMantenimientoTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoTipo.setText("Tipo:");

        lblMantenimientoStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoStock.setText("Saldo:");

        txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtSaldo.setEnabled(false);

        lblMantenimientoNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoNombre.setText("Monto:");

        lblMantenimientoCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoCodigo.setText("Codigo:");

        txtMonto.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        lblMantenimientoCodigo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoCodigo2.setText("Codigo Cuenta:");

        lblMantenimientoTipo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMantenimientoTipo1.setText("Fecha:");

        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtFecha.setEnabled(false);

        javax.swing.GroupLayout pnlDatosMovLayout = new javax.swing.GroupLayout(pnlDatosMov);
        pnlDatosMov.setLayout(pnlDatosMovLayout);
        pnlDatosMovLayout.setHorizontalGroup(
            pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosMovLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMantenimientoCodigo)
                    .addComponent(lblMantenimientoTipo)
                    .addComponent(lblMantenimientoTipo1)
                    .addComponent(lblMantenimientoNombre)
                    .addComponent(lblMantenimientoStock)
                    .addComponent(lblMantenimientoCodigo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodigoCuenta)
                    .addComponent(txtFecha)
                    .addComponent(txtMonto)
                    .addComponent(txtSaldo)
                    .addComponent(txtCodigo)
                    .addComponent(jcmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlDatosMovLayout.setVerticalGroup(
            pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosMovLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMantenimientoCodigo))
                .addGap(14, 14, 14)
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMantenimientoCodigo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMantenimientoTipo)
                    .addComponent(jcmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMantenimientoTipo1))
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosMovLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosMovLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblMantenimientoNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMantenimientoStock))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMantenimientoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIngresarID)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarCI, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClienteBuscarCI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jcmbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pnlDatosMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(59, 59, 59)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMantenimientoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClienteBuscarCI, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngresarID))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcmbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatosMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarCIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCIKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9'){
            evt.consume();
        }else{
            if(txtBuscarCI.getText().length() > 13){
                evt.consume();
                JOptionPane.showMessageDialog(null, "Dato ingresado incorrecto");
            }
        }
    }//GEN-LAST:event_txtBuscarCIKeyTyped

    private void btnClienteBuscarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteBuscarCIActionPerformed
        try{
            if(txtBuscarCI.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Debe ingresar el número de cédula.");
            }else{
                if(cli.validarCedula(txtBuscarCI.getText()) == true){
                    obj.buscarCuenta(jcmbCuenta,txtBuscarCI.getText());
                    txtBuscarCI.setText("");
                    jcmbTipo.enable(true);
                    txtMonto.enable(true);
                }else{
                    txtBuscarCI.setText("");
                }
            }
        }catch (Exception ex){

        }
    }//GEN-LAST:event_btnClienteBuscarCIActionPerformed

    private void btnMovEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovEliminarActionPerformed

    private void btnMovGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovGuardarActionPerformed
        String tipo = jcmbTipo.getSelectedItem().toString().substring(0,3).toUpperCase();
        float monto = Float.parseFloat(txtMonto.getText());
        txtSaldo.setText("0.00");
        Movimientos obj = new Movimientos(txtCodigoCuenta.getText(),tipo,monto,Float.parseFloat(txtSaldo.getText()));
        obj.registrarMov(txtSaldo);
    }//GEN-LAST:event_btnMovGuardarActionPerformed

    private void btnMovNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovNuevoActionPerformed
        Limpiar();
        btnMovGuardar.setEnabled(true);
    }//GEN-LAST:event_btnMovNuevoActionPerformed

    private void btnMovSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnMovSalirActionPerformed

    private void jcmbCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCuentaActionPerformed
        txtCodigoCuenta.setText(jcmbCuenta.getSelectedItem().toString());
    }//GEN-LAST:event_jcmbCuentaActionPerformed

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'&&evt.getKeyChar()!='-'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&& txtMonto.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDMovimientos dialog = new JDMovimientos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteBuscarCI;
    private javax.swing.JButton btnMovEliminar;
    private javax.swing.JButton btnMovGuardar;
    private javax.swing.JButton btnMovNuevo;
    private javax.swing.JButton btnMovSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcmbCuenta;
    private javax.swing.JComboBox<String> jcmbTipo;
    private javax.swing.JLabel lblIngresarID;
    private javax.swing.JLabel lblMantenimientoCodigo;
    private javax.swing.JLabel lblMantenimientoCodigo2;
    private javax.swing.JLabel lblMantenimientoNombre;
    private javax.swing.JLabel lblMantenimientoStock;
    private javax.swing.JLabel lblMantenimientoTipo;
    private javax.swing.JLabel lblMantenimientoTipo1;
    private java.awt.Panel panel1;
    private javax.swing.JPanel pnlDatosMov;
    private java.awt.Panel pnlMantenimientoTitulo;
    private javax.swing.JTextField txtBuscarCI;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCuenta;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
